# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ece19123756ad4ed91d180b7dff443f0f0500cc648bb33b795f3dfba1d2bfbf105465e0273920869b46aa857f4e0f3ede5de40666c1a9ec38460151a2cc48af4

test:
  secret_key_base: c56c99d996aa31cd6fceb1c69ea6fb5f323f4c680f3f2c959dd532b907795b12bcf91390a91325699541d25ac567a306143a15dcf2769f2c2a891445cab6eeff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
